<?php
$base_url = $this->basePath();
?>

<div class="row banner_2_login">
    <div class="col-lg-offset-3 col-lg-6 col-md-12 col-xs-12 font-principal well" style="margin-top: 20px">
        <div class="col-sm-offset-2 col-lg-8 col-md-8 col-sm-8 col-xs-12 col-sm-12">
        	<div class="col-md-12" style="border: 3px solid; color: #69C7C1;"></div>
            <h3 class="text-left"><b style="color: #69C7C1">INICIAR SESIÓN  </b><img src="<?php echo $base_url; ?>/img/interrogacion.png" class="signo-inte"></h3>

        </div> 
        <div class="col-sm-offset-2 col-lg-8 col-md-8 col-sm-8 col-xs-12 col-sm-12">       
            <div class="box_login">

                <div class="center_div">
                    <form id="usuario_sec_frm_login" method="POST" action="<?php echo $this->url('usuario/sec', array('action' => 'validate')); ?>" class="form-horizontal">

                        <div class="form-group">
                            <label class="col-lg-12 col-md-12 col-sm-12 col-xs-12 lbl_login_">Usuario:</label>
                            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                <input type="text" class="form-control input_frm" id="usuario_sec_documento" name="usuario_sec_documento" autocomplete="off" maxlength="<?php echo $apps_usuario['num_caracteres']['documento_identidad']['max']; ?>" placeholder="DNI/USUARIO">
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="inputPassword" class="col-lg-12 col-md-12 col-sm-12 col-xs-12 lbl_login_">Contrase&ntilde;a:</label>
                            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                <input type="password" id="usuario_sec_password" name="usuario_sec_password" class="form-control input_frm" autocomplete="off" maxlength="<?php echo $apps_usuario['num_caracteres']['contrasenias']['max']; ?>" placeholder="CONTRASEÑA">
                            </div>
                        </div>

                        <?php
                        if ($apps_usuario['num_caracteres']['captcha']['enabled'] === true)
                        {
                            ?>
                            <div class="form-group">
                                <div class="col-md-12" style="text-align: center;">
                                    <img id="ref_login" src="<?php echo $base_url ?>/usuario/captcha/logincaptcha?rnd=<?php echo rand(); ?>"/>
                                    <a href="javascript:" onclick="refresh_login()" data-toggle="tooltip" title="Actualizar" ><span class="glyphicon glyphicon-refresh" style="font-size: 20px; color: #660f38; top: 5px;"></span></a>
                                </div>
                            </div>

                            <div class="form-group">
                                <label class="col-xs-12 lbl_login_"  for="inputCodigo" >C&oacute;digo de la imagen:</label>
                                <div class="col-xs-12">
                                    <input type="text" class="form-control input_frm" id="usuario_sec_captcha_login" name="usuario_sec_captcha_login" autocomplete="off" maxlength="<?php echo $apps_usuario['num_caracteres']['captcha']['tamano_codigo']; ?>" style="text-transform:uppercase">
                                </div>
                            </div>
                            <?php
                        }
                        if (count($msgs) > 0)
                        {
                            foreach ($msgs as $msg)
                            {
                                echo($msg);
                            }
                        }
                        ?>

                        <div class="form-group">
                            <div class="col-md-12">
                                <button id="usuario_sec_login" type="submit" class="btn col-xs-12 btn-login">INGRESAR <i class="glyphicon glyphicon-chevron-right"></i></button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
            <div class="col-md-12" style="border: 3px solid; color: #69C7C1; margin-top:20px;"></div>
        </div>
    </div>
</div>