<?php
$base_url = $this->basePath();
?>
<style type="text/css">
    #wrap_formato{
        background-color: #FFF;
        overflow: hidden;
        margin-bottom: 150px;
        width: 1050px;
        font-family: tahoma;
    }

    table {
        border-collapse: collapse;
        width: 100%;
    }

    th, td {
        text-align: left;
        padding: 8px;
    }

    tr:nth-child(even){background-color: #f2f2f2}

    th {
        background-color: #4CAF50;
        color: white;
    }
</style>

<div id="wrap_formato">
    <table style="width: 95%;">
        <tbody>
            <tr>
                <td style="width:50%;text-align:center;">
                    <img  width="200px" src="<?php echo $base_url; ?>/img/indago.png"/>
                </td>
                <td style="width:50%;text-align:center;">
                    <img src="<?php echo $base_url; ?>/img/logo-minedu.png" />
                </td>
            </tr>
        </tbody>
    </table>

    <table style="margin: 5px 10px 0px 10px; width: 95%;">
        <tbody>
            <tr>
                <td style="text-align: center;"><h1>LISTA DE INFORMANTES POR INSTRUMENTO</h1>         
                </td>
            </tr>
        </tbody>
    </table>
    <table style="margin: 5px 10px 0px 10px; width: 95%;">
        <tbody>
            <tr>
                <td style="text-align: left;"><b>Nombre de instrumento:</b></td>
                <td style="text-align: left;"><?=$datos[0]['NOMBRE']?></td>
            </tr>
        </tbody>
    </table>
    <table id="tbl_header">
        <thead>
            <tr>
                <th><b>Institución educativa</b></th>
                <th><b>Informantes(Nombres y apellidos)</b></th>
                <th><b>Estado</b></th>
            </tr>
        </thead>
        <tbody>
        <?php
        
        foreach ($datos_instrumento as $lis) {
            ?>
        <tr>
            <td> <?= $lis['institucion_educativa'] ?> </td> 
            <td> <?= $lis['informante'] ?> </td>
            <td> <?= $lis['estado'] ?> </td>
          </tr>  
            <?php
        }
        ?>  
        </tbody>
    </table>


</div>
