<?php
echo $this->doctype();
$base_url = $this->basePath();
$apps_var = $this->apps_var;
$usuario = $this->users_acl->rows;
$apps_var_usuario = $this->apps_config_caracteres;
$cambio_config = $this->cambio_config;
?>

<html lang="en">
    <head>
        <meta charset="utf-8">

        <?php echo $this->headTitle($apps_var['app_title'])->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php
        echo $this->headMeta()
                ->appendName('viewport', 'width=device-width, initial-scale=1.0')
                ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>
        
        <link rel="shortcut icon" href="<?php echo $base_url; ?>/img/favicon.ico" type="image/x-icon">
	<link rel="icon" href="<?php echo $base_url; ?>/img/favicon.ico" type="image/x-icon">
        <!-- Le styles -->
        <?php
//        echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
        echo $this->headLink()
                ->prependStylesheet($this->basePath('css/style.css'))
                ->prependStylesheet($this->basePath('js/lib/jqgrid/css/ui.jqgrid-bootstrap.css'))
                ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
                ->prependStylesheet($this->basePath('css/bootstrap-slider.css'))
                ->prependStylesheet($this->basePath('css/font-awesome.min.css'))
                ->prependStylesheet($this->basePath('css/awesome-bootstrap-checkbox.css'))
                ->prependStylesheet($this->basePath('css/jquery-ui.css'))
        ?>

        <script type="text/javascript">
            var root = '<?php echo $base_url; ?>';
            var min_clave = <?php echo $apps_var_usuario['contrasenias']['min']; ?>;
            var max_clave = <?php echo $apps_var_usuario['contrasenias']['max']; ?>;
            var tam_captcha = <?php echo $apps_var_usuario['captcha']['tamano_codigo']; ?>;
            var min_dni = <?php echo $apps_var_usuario['documento_identidad']['min']; ?>;
            var max_dni = <?php echo $apps_var_usuario['documento_identidad']['max']; ?>;
            var max_correo = <?php echo $apps_var_usuario['general']['correo']; ?>;
            var token_sms = <?php echo $apps_var_usuario['general']['token_sms']; ?>;
        </script>
        <!-- Scripts -->        
        <?php
        echo $this->headScript()
                ->prependFile($this->basePath('js/app/menu_datos_usuario.js?v=' . md5(time())))
                ->prependFile($this->basePath('js/app/menu_presentacion.js?v=' . md5(time())))
//                ->prependFile($this->basePath('js/app/m_config_instrumentos.js?v=' . md5(time())))
                ->prependFile($this->basePath('js/app/m_config_informantes.js?v=' . md5(time())))
                ->prependFile($this->basePath('js/app/m_config_programacion.js?v=' . md5(time())))
                ->prependFile($this->basePath('js/app/menu_reportes.js?v=' . md5(time())))
                ->prependFile($this->basePath('js/app/menu_seleccion.js?v=' . md5(time())))
                ->prependFile($this->basePath('js/app/menu.js?v=' . md5(time())))
                ->prependFile($this->basePath('js/app/app.js?v=' . md5(time())))
                ->prependFile($this->basePath() . '/d.js?v=' . md5(time()))
                ->prependFile($this->basePath('js/lib/input-mask/jquery.inputmask.date.extensions.js'))
                ->prependFile($this->basePath('js/lib/input-mask/jquery.inputmask.extensions.js'))
                ->prependFile($this->basePath('js/lib/input-mask/jquery.inputmask.js'))
                ->prependFile($this->basePath('js/lib/js/jquery.jqGrid.min.js'))
                ->prependFile($this->basePath('js/lib/js/i18n/grid.locale-es.js'))
                ->prependFile($this->basePath('js/app/_strings.js'))
                ->prependFile($this->basePath('js/lib/bootbox.min.js'))
                ->prependFile($this->basePath('js/lib/kakashi.js'))
                ->prependFile($this->basePath('js/lib/naruto.js'))
                ->prependFile($this->basePath('js/lib/porigon.js'))
                ->prependFile($this->basePath('js/data.js'))
                ->prependFile($this->basePath('js/drilldown.js'))
                ->prependFile($this->basePath('js/exporting.js'))
                ->prependFile($this->basePath('js/highcharts-3d.js'))
                ->prependFile($this->basePath('js/highcharts.js'))
                ->prependFile($this->basePath('js/lib/handlebars-v4.0.5.js'))
                ->prependFile($this->basePath('js/lib/BaseXJS/jquery.filter_input.js'))
                ->prependFile($this->basePath('js/lib/BaseXJS/jquery.commons.js'))
                ->prependFile($this->basePath('js/lib/BaseXJS/BaseX.js'))
                ->prependFile($this->basePath('js/bootstrap.min.js'))
                ->prependFile($this->basePath('js/bootstrap-slider.js'))
                ->prependFile($this->basePath('js/lib/jquery-ui.js'))
                ->prependFile($this->basePath('js/jquery.min.js'))
                ->prependFile($this->basePath('js/respond.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
                ->prependFile($this->basePath('js/html5shiv.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
        ;
        ?>
    </head>
    <body class="body_bg">
    	<div class="container">
        <div class="row row-fluid">
            <div class="col-md-12 banner_top_titulo">
                <div class="col-md-6 col-sm-6 col-xs-12 left_side">
                    <a href="<?php echo $base_url; ?>" class="text-center">
                        <img class="img-responsive img_logo" src="<?php echo $base_url; ?>/img/indago.png"/>
                    </a>  
                </div>
                <div class="col-md-6 col-sm-6 col-xs-12 right_side">
                    <a target="_blank" href="http://www.minedu.gob.pe/" class="text-center">
                        <img class="img-responsive" src="<?php echo $base_url; ?>/img/logo_ministerio_educacion.gif"/>
                    </a>
                </div>
            </div>
        </div>
        </div>
        
        <div class="row dashboard_barra_top">
        <div class="container">
        	<div class="col-md-9 padtop10">
                <div class="col-md-6 text-center" id="tbi_name_display">
                    Usuario(a): <?php echo $usuario->display_name; ?>
                </div>
                <div class="col-md-2 text-center">
                    Rol: <?php echo $usuario->rol; ?>
                    <input type="hidden" id="hdn_sesion_token" name="hdn_sesion_token" value="<?php echo $this->token_sesion; ?>" />
                </div> 
    
                <div class="col-md-4 text-center" >            
                    Último acceso: 
                    <?php 
                        $fec_ult_acceso = $usuario->fec_ultimo_acceso;
                        $fec_ult_acceso_format = date("d/m/Y", strtotime($fec_ult_acceso));
                        echo $fec_ult_acceso_format; 
                    ?>
                </div>
            </div>
            <div class="col-md-3">
                <div class="col-xs-12 text-center">
                    <button type="button" class="btn btn_primary_in btn-md" id="btn_change_password">
                        <span class="glyphicon glyphicon-cog" aria-hidden="true"></span>
                    </button>
                    <a id="btn_cerrar_sesion" type="button" class="btn btn_primary_in" href="<?php echo $this->url('usuario/sec', array('action' => 'logout')); ?>">Cerrar Sesión</a>
                </div>
            </div>
        </div>
        </div>
        
        <div class="container">
            <?php
//            echo $this->partial('_menu.phtml', []);
            ?>
            <?php echo $this->content; ?>
            <!--<hr>-->
        </div> <!-- /container -->
        <div class="modal fade" id="modal_chg_password" aria-hidden="true" >
            <div class="modal-dialog">
                <div id="passwordreset" style="margin-top:40px;" class="mainbox col-md-12">
                    <div class="panel panel-primary">
                        <div class="panel-heading">
                            <div class="panel-title">Cambiar contraseña</div>
                        </div>                     
                        <div class="panel-body">
                            <form id="frm_change_password" class="form-horizontal" role="form" autocomplete="off">
                                <div class="form-group">
                                    <label for="email" class=" control-label col-sm-5">Contraseña actual</label>
                                    <div class="col-sm-7">
                                        <input type="password" class="form-control" name="pass_current" id="pass_current" placeholder="contraseña actual">
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label for="email" class=" control-label col-sm-5">Nueva contraseña</label>
                                    <div class="col-sm-7">
                                        <input type="password" class="form-control" name="pass_new" id="pass_new" placeholder="crear nueva contraseña">
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label for="email" class=" control-label col-sm-5">Confirmar nueva contraseña</label>
                                    <div class="col-sm-7">
                                        <input type="password" class="form-control" name="pass_confirmation" id="pass_confirmation" placeholder="confirmar nueva contraseña">
                                    </div>
                                </div>
                                <div class="form-group">
                                    <!-- Button -->                                 
                                    <div class="  col-sm-offset-5 col-sm-7">
                                        <button id="btn_change_password_save" type="button" class="btn btn-login">Aceptar</button>
                                        <button type="button" data-dismiss="modal" aria-label="Close" class="btn btn-login">Cancelar</button>
                                    </div>
                                </div>                             
                            </form>
                        </div>
                    </div>
                </div>   
            </div>
        </div>
        <footer class="footer">
            <div class="container">
                <div class="col-md-12 text-center">
                    <br />
                    <p class="footer_color">
                         &copy; Derechos reservados <?php echo date('Y'); ?> - MINEDU – AP Móvil v.1.0
                    </p>
                </div>
                <!--<div class="clearfix"></div>-->
            </div>
        </footer>
        <?php echo $this->inlineScript() ?>
        <!--<script type='text/javascript' src="//cdnjs.cloudflare.com/ajax/libs/modernizr/2.7.1/modernizr.min.js"></script>-->
        <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!--[if lt IE 9]>
          <script type='text/javascript' src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
          <script type='text/javascript' src="//cdnjs.cloudflare.com/ajax/libs/respond.js/1.4.2/respond.js"></script>
        <![endif]-->
        <script>
<?php echo $apps_var['google_analytics_code']; ?>
        </script>
    </body>
</html>
