<style>
    .form-horizontal .form-group {
        margin-left: 0px !important; 
        margin-right: 0px !important; 
    }

</style>
<div class="row" style="margin-top: 10px;">
    <div class="col-sm-6">
        <ol class="breadcrumb">
            <li><a href="#">Inicio</a></li>
            <li class="active">Instrumentos</li>
        </ol>
    </div>  
    <div class="col-sm-6" style="text-align: right;">
            
    </div>  
</div>
<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-primary">
            <div class="panel-heading">Avanzado</div>
            <div class="panel-body">
                <div id="dv_container_pastel" style="height: 400px">
                    
                </div>
                <div id="dv_container_barras" style="height: 400px">
                    
                </div>
            </div>
        </div>
    </div>
</div>

