<style>
    .form-horizontal .form-group {
        margin-left: 0px !important; 
        margin-right: 0px !important; 
    }
    div#tpl_info {
        font-size: 12px;
    }
	hr {
		border: 1px solid #69c7c1 !important;
   	 	margin-bottom: 5px !important;
    	width: 96%;
    	margin: 0 auto;
   }
   .texttitle{
		color:#25b7d3; 
		margin-bottom:20px;}

</style>

<div class="row" style="margin-top: 20px;">
    <div class="col-sm-6">
        <ol class="breadcrumb">
            <li><a href="">Inicio</a></li>
            <li><a href="<?php echo $this->url('inicio', array('action' => 'index')); ?>">Configuracion</a></li>
            <li class="active">Informantes</li>
        </ol>
    </div>  
    <div class="col-sm-6" style="text-align: right;">
    </div>  
</div>
<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-primary">
            <div class="panel-heading">Instrumentos</div>
            <div class="panel-body">
				<div class="col-md-10"><h3 class="texttitle">Lista de Informantes</h3></div>
                <div class="col-md-2">
                	<div style="text-align:right;">
                        <button type="button" class="btn btn-login" id="btn_search_ins" name="btn_search_ins">
                            <span class="glyphicon glyphicon-plus"></span> AGREGAR</button>
                    </div>
                </div>
                <form class="form-horizontal" id="frm_instrumento">
                    <div class="form-group">
                        <label class="control-label-login col-md-3">DRE:</label>
                        <div class="col-md-4">
                            <select name="lista_dre" id="lista_dre" class="form-control">
                                <option value="">--Seleccione--</option>
                                <?php
                                foreach ($estrategia as $e) {
                                    ?>
                                    <option value="<?php echo $e['ID_TIPO_ESTRATEGIA']; ?>"><?php echo $e['NOMBRE']; ?></option>
                                    <?php
                                }
                                ?>
                            </select>
                        </div>
                        <label class="control-label-login col-md-2">UGEL:</label>
                        <div class="col-md-3">
                            <select name="lista_ugel" id="lista_ugel" class="form-control">
                                <option value="">--Seleccione--</option>
                                <?php
                                foreach ($intervencion as $i) {
                                    ?>
                                    <option value="<?php echo $i['ID_TIPO_INTERVENCION']; ?>"><?php echo $i['NOMBRE']; ?></option>
                                    <?php
                                }
                                ?>
                            </select>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label-login col-md-3">Institución Educativa:</label>
                        <div class="col-md-9">
                        	<div class="input-group">
                            	<input type="text" class="form-control" id="InstitucionEducativa" placeholder="Institución Educativa">
                            	<div class="input-group-addon"><span class="glyphicon glyphicon-search"></span></div>
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label-login col-md-3">DNI / Apellidos y Nombres:</label>
                        <div class="col-md-9">
                        	<div class="input-group">
                            	<input type="text" class="form-control" id="DNIApeNombres" placeholder="Apellidos y Nombres">
                            	<div class="input-group-addon"><span class="glyphicon glyphicon-search"></span></div>
                            </div>
                        </div>
                    </div>
                    
                    <div class="form-group">
                        <div class="col-md-5">
                        </div>
                        <div class="col-md-7 text-right">
                            <button type="button" class="btn btn-login" id="btn_search_ins" name="btn_search_ins">
                                <span class="glyphicon glyphicon-search"></span>
                                BUSCAR</button>
                            <button type="button" class="btn btn-login" id="btn_limpiar_ins" name="btn_limpiar_ins">
                                <span class="glyphicon glyphicon-erase"></span>
                                LIMPIAR</button>
                        </div>
                    </div> 
                </form>
            </div>
        </div>
    </div>
</div>
<hr>
<div class="col-md-12" style="font-size:20px; margin-bottom:15px;">
    <div class="col-md-10 texttitle">Resultados de la Búsqueda</div>
    <div class="col-md-2" style="text-align:right;">
        <a href="#"><span class="fa fa-file-excel-o"></span></a>
        <a href="#"><span class="fa fa-file-pdf-o"></span></a>
    </div>                
</div>
<div class="col-lg-12">
    <table id="grid_instrumentos">
    </table>
    <div id="pager_grid_instrumentos"></div>
</div>

<div class="modal fade" id="modal_agrega_inf" aria-hidden="true" style="overflow-y: hidden">
    <div class="modal-dialog modal-lg" style="min-width: 200px; ">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">Agregar Informante</h4>
            </div>
            <div class="modal-body" style="display: block; overflow-y: auto;">
                <div id="content_out">
                    <div id="dv_container_agregar">
						<form class="form-horizontal" id="frm_agregarinf">
                            <div class="form-group">
                                <label class="control-label-login col-md-3">DRE:</label>
                                <div class="col-md-4">
                                    <select name="lista_dre" id="lista_dre" class="form-control">
                                        <option value="">--Seleccione--</option>
                                    </select>
                                </div>
                                <label class="control-label-login col-md-2">UGEL:</label>
                                <div class="col-md-3">
                                    <select name="lista_ugel" id="lista_ugel" class="form-control">
                                        <option value="">--Seleccione--</option>
                                    </select>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="control-label-login col-md-3">Institución Educativa:</label>
                                <div class="col-md-9">
                                    <div class="input-group">
                                        <input type="text" class="form-control" id="InstitucionEducativa" placeholder="Institución Educativa">
                                        <div class="input-group-addon"><span class="glyphicon glyphicon-search"></span></div>
                                    </div>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="control-label-login col-md-3">DNI</label>
                                <div class="col-md-2">
                                    <div class="input-group">
                                        <input type="text" class="form-control" id="DNI" placeholder="DNI">
                                    </div>
                                </div>
                                <label class="control-label-login col-md-3">Apellidos y Nombres</label>
                                <div class="col-md-4">
                                    <div class="input-group">
                                        <input type="text" class="form-control" id="ApellidosNombres" placeholder="Apellidos y Nombres">
                                    </div>
                                </div>
                            </div>                            
                            <div class="form-group">
                                <div class="col-md-5">
                                </div>
                                <div class="col-md-7 text-right">
                                    <button type="button" class="btn btn-login" id="btn_search_ins" name="btn_search_ins">
                                        <span class="glyphicon glyphicon-search"></span>
                                        BUSCAR</button>
                                    <button type="button" class="btn btn-login" id="btn_limpiar_ins" name="btn_limpiar_ins">
                                        <span class="glyphicon glyphicon-erase"></span>
                                        LIMPIAR</button>
                                </div>
                            </div>
                            
                            <hr>
                            
                            <div class="col-lg-12">
                                <table id="grid_instrumentos">
                                </table>
                                <div id="pager_grid_instrumentos"></div>
                            </div>
                            
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
