<style>
    .form-horizontal .form-group {
        margin-left: 0px !important; 
        margin-right: 0px !important; 
    }
    div#tpl_info {
        font-size: 12px;
    }
	hr {
		border: 1px solid #69c7c1 !important;
   	 	margin-bottom: 5px !important;
    	width: 96%;
    	margin: 0 auto;
   }
   .texttitle{
		color:#25b7d3; 
		margin-bottom:20px;}
</style>

<div class="row" style="margin-top: 20px;">
    <div class="col-sm-6">
        <ol class="breadcrumb">
             <li><a href="">Inicio</a></li>
            <li><a href="<?php echo $this->url('inicio', array('action' => 'index')); ?>">Configuracion</a></li>
            <li class="active">Programación de instrumentos</li>
        </ol>
    </div>  
    <div class="col-sm-6" style="text-align: right;">
    </div>  
</div>
<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-primary">
            <div class="panel-heading">Programación de Instrumento</div>
            <div class="panel-body">
				<div class="col-md-12">
                	<div style="text-align:right; margin-bottom:20px;">
                        <button type="button" class="btn btn-login" id="btn_search_ins" name="btn_search_ins">
						<span class="glyphicon glyphicon-plus"></span> AGREGAR</button>
                    </div>
                </div>
                <form class="form-horizontal" id="frm_instrumento">
                    <div class="form-group">
                        <label class="control-label-login col-md-2">Año:</label>
                        <div class="col-md-4">
                            <select name="lista_anio" id="lista_anio" class="form-control">
                                <option value="">--Seleccione--</option>
                            </select>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label-login col-md-2">Estrategia:</label>
                        <div class="col-md-4">
                            <select name="lista_estrategia" id="lista_estrategia" class="form-control">
                                <option value="">--Seleccione--</option>
                            </select>
                        </div>
                        <label class="control-label-login col-md-2">Intervención:</label>
                        <div class="col-md-4">
                            <select name="lista_intervencion" id="lista_intervencion" class="form-control">
                                <option value="">--Seleccione--</option>
                            </select>
                        </div>
                    </div> 
                    <div class="form-group">
                        <label class="control-label-login col-md-2">Fase:</label>
                        <div class="col-md-4">
                            <select name="lista_fase" id="lista_fase" class="form-control">
                                <option value="">--Seleccione--</option>
                            </select>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label-login col-md-2">Fecha Inicio:</label>
                        <div class="col-md-4">
                            <div class="form-group">
								<input type="text" class="form-control" name="datetimepicker1" id="datetimepicker1" placeholder="dd/mm/yyyy" data-inputmask="'alias': 'dd/mm/yyyy'" data-mask="">         
                            </div>
                        </div>
                        <label class="control-label-login col-md-2">Fecha Fin:</label>
                        <div class="col-md-4">
                            <div class="form-group">
								<input type="text" class="form-control" name="datetimepicker2" id="datetimepicker2" placeholder="dd/mm/yyyy" data-inputmask="'alias': 'dd/mm/yyyy'" data-mask="">           
                            </div>
                        </div>
                    </div> 
                    
                    <div class="form-group">
                        <div class="col-md-5">
                        </div>
                        <div class="col-md-7 text-right">
                            <button type="button" class="btn btn-login" id="btn_search_ins" name="btn_search_ins">
                                <span class="glyphicon glyphicon-search"></span>
                                BUSCAR</button>
                            <button type="button" class="btn btn-login" id="btn_limpiar_ins" name="btn_limpiar_ins">
                                <span class="glyphicon glyphicon-erase"></span>
                                LIMPIAR</button>
                        </div>
                    </div> 
                </form>
            </div>
        </div>
    </div>
</div>
<hr>
<div class="col-md-12" style="font-size:20px; margin-bottom:15px;">
    <div class="col-md-10 texttitle">Resultados de la Búsqueda</div>
    <div class="col-md-2" style="text-align:right;">
        <a href="#"><span class="fa fa-file-excel-o"></span></a>
        <a href="#"><span class="fa fa-file-pdf-o"></span></a>
    </div>                
</div>
<div class="col-lg-12">
    <table id="grid_instrumentos">
    </table>
    <div id="pager_grid_instrumentos"></div>
</div>


<div class="modal fade" id="modal_resumen_tmp" aria-hidden="true" style="overflow-y: hidden">
    <div class="modal-dialog modal-lg" style="min-width: 200px; ">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">Agregar Programación</h4>
            </div>
            <div class="modal-body" style="display: block; overflow-y: auto;">
                <div id="content_out">
                    <div id="dv_container_programacion">
						<form class="form-horizontal" id="frm_instrumento">
                            <div class="form-group">
                                <label class="control-label-login col-md-3">Año:</label>
                                <div class="col-md-9">
                                    <select name="lista_anio" id="lista_anio" class="form-control">
                                        <option value="">--Seleccione--</option>
                                    </select>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="control-label-login col-md-3">Nombre de Instrumento:</label>
                                <div class="col-md-9">
                                    <select name="lista_instrumento" id="lista_instrumento" class="form-control">
                                        <option value="">--Seleccione--</option>
                                    </select>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="control-label-login col-md-3">Frecuencia de Corte:</label>
                                <div class="col-md-9">
                                    <label class="radio-inline">
                                      <input type="radio" name="inlineRadioOptions" id="inlineRadio1" value="option1"> Semenal </label>
                                    <label class="radio-inline">
                                      <input type="radio" name="inlineRadioOptions" id="inlineRadio2" value="option2"> Mensual </label>
                                    <label class="radio-inline">
                                      <input type="radio" name="inlineRadioOptions" id="inlineRadio3" value="option3"> Anual </label>
                                </div>
                            </div>
                            <hr>
                            <div class="form-group">
                                <label class="control-label-login col-md-3">Primer Período:</label>
                                <div class="col-md-9">
									<div class="col-md-6">
                                    	<label for="fdesde" class="col-md-4 control-label">Fecha desde</label>
                                        <input type="text" class="form-control" name="datetimepicker3" id="datetimepicker3" placeholder="dd/mm/yyyy" data-inputmask="'alias': 'dd/mm/yyyy'" data-mask="">  
                                    </div>
                                    <div class="col-md-6">
                                    	<label for="fdesde" class="col-md-4 control-label">Fecha hasta</label>
                                        <input type="text" class="form-control" name="datetimepicker4" id="datetimepicker4" placeholder="dd/mm/yyyy" data-inputmask="'alias': 'dd/mm/yyyy'" data-mask="">  
                                    </div>
                                </div>
                            </div>
                            
                            <div class="form-group">
                                <div class="col-md-5">
                                </div>
                                <div class="col-md-7 text-right">
                                    <button type="button" class="btn btn-login" id="btn_search_ins" name="btn_search_ins">
                                        <span class="glyphicon glyphicon-remove"></span>
                                        CANCELAR</button>
                                    <button type="button" class="btn btn-login" id="btn_limpiar_ins" name="btn_limpiar_ins">
                                        <span class="glyphicon glyphicon-floppy-disk"></span>
                                        GUARDAR</button>
                                </div>
                            </div>
						</form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
