<?php
$base_url = $this->basePath();
?>
<style>
    .form-horizontal .form-group {
        margin-left: 0px !important; 
        margin-right: 0px !important; 
    }
    div#tpl_info {
        font-size: 12px;
    }
</style>
<div class="row" style="margin-top: 20px;">
    <div class="col-sm-6">
        <ol class="breadcrumb">
            <li><a href="#">Inicio</a></li>
            <li class="active">Instrumentos</li>
        </ol>
    </div>  
    <div class="col-sm-6" style="text-align: right;">
            <!--<button type="button" class="btn btn-default btn-sm"><span class="glyphicon glyphicon-backward" aria-hidden="true"></span> Atrás</button>-->
    </div>  
</div>
<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-primary">
            <div class="panel-heading">Información del instrumento</div>
            <div class="panel-body">

                <form class="form-horizontal" id="frm_instrumento">
                    <div class="form-group">
                        <div class="col-md-5">
                        </div>
                        <div class="col-md-7 text-right">
                            <button type="button" class="btn btn-login" id="btn_new_ins" name="btn_new_ins">
                                <span class="glyphicon glyphicon-plus"></span>
                                NUEVO</button>
                        </div>
                    </div> 
                    <div class="form-group">
                        <label class="control-label-login col-md-2">Estrategia:</label>
                        <div class="col-md-4">
                            <select name="lista_estrategia" id="lista_estrategia" class="form-control">
                                <option value="">--Seleccione--</option>
                                <?php
                                foreach ($estrategia as $e) {
                                    ?>
                                    <option value="<?php echo $e['ID_TIPO_ESTRATEGIA']; ?>"><?php echo $e['NOMBRE']; ?></option>
                                    <?php
                                }
                                ?>
                            </select>
                        </div>
                        <label class="control-label-login col-md-2">Intervención:</label>
                        <div class="col-md-4">
                            <select name="lista_intervencion" id="lista_intervencion" class="form-control">
                                <option value="">--Seleccione--</option>
                                <?php
                                foreach ($intervencion as $i) {
                                    ?>
                                    <option value="<?php echo $i['ID_TIPO_INTERVENCION']; ?>"><?php echo $i['NOMBRE']; ?></option>
                                    <?php
                                }
                                ?>
                            </select>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label-login col-md-2">Ámbito:</label>
                        <div class="col-md-4">
                            <!--<select name="lista_dre_ins" id="lista_dre_ins" class="form-control">-->
                            <select name="lista_ambito" id="lista_ambito" class="form-control">
                                <option value="">--Seleccione--</option>
                                <?php
                                foreach ($ambito as $d) {
                                    ?>
                                    <option value="<?php echo $d['ID_TIPO_AMBITO']; ?>"><?php echo $d['NOMBRE']; ?></option>
                                    <?php
                                }
                                ?>

                            </select>
                        </div>
                        <label class="control-label-login col-md-2">Muestra:</label>
                        <div class="col-md-4">
                            <select name="lista_muestra" id="lista_muestra" class="form-control">
                                <option value="">--Seleccione--</option>
                                <?php
                                foreach ($muestra as $d) {
                                    ?>
                                    <option value="<?php echo $d['ID_TIPO_MUESTRA']; ?>"><?php echo $d['NOMBRE']; ?></option>
                                    <?php
                                }
                                ?>
                            </select>
                        </div>
                    </div> 
                    <div class="form-group">
                        <div class="col-md-5">
                        </div>
                        <div class="col-md-7 text-right">
                            <button type="button" class="btn btn-login" id="btn_search_ins" name="btn_search_ins">
                                <span class="glyphicon glyphicon-search"></span>
                                BUSCAR</button>
                            <button type="button" class="btn btn-login" id="btn_limpiar_ins" name="btn_limpiar_ins">
                                <span class="glyphicon glyphicon-erase"></span>
                                LIMPIAR</button>
                        </div>
                    </div> 
                </form>
            </div>
        </div>
    </div>
</div>
<!--<div class="row">
    <div class="col-md-12" style="font-size:20px; margin-bottom:15px;text-align:right;">
            <a href="#"><span class="fa fa-file-excel-o"></span></a>
            <a href="<?php echo $base_url;?>/seleccion/index/pdfdw" target="_blank"><span class="fa fa-file-pdf-o"></span></a>               
    </div>
</div>-->
<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-primary">
            <div class="panel-heading">
                Resultados de la búsqueda
            </div>

            <div class="panel-body">
                <div class="col-lg-12">
                    <table id="listar_grid_instrumentos">
                    </table>
                    <div id="pager_listar_grid_instrumentos"></div>
                </div>
            </div>
        </div>
    </div>
</div>