<div class="row">
    <div>
        <ol class="breadcrumb">
            <li><a href="#">Inicio</a></li>
            <li class="active">Preguntas frecuentes</li>
        </ol>
    </div>    
</div>
<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-primary">
            <div class="panel-heading">Preguntas frecuentes</div>
            <div class="panel-body">
                <?= file_get_contents(__DIR__ . '/formato_pf.html'); ?>
                <br>
                <br>
                <div id="content_out" style="padding: 20px"></div>
            </div>
        </div>
    </div>
</div>

