<style>
    .title_lbl{
        color:#333;
    }
</style>
<?php
$base_url = $this->basePath();
$informacion = [];
if (count($info) > 0) {
    $informacion = $info[0];
}
?>
<form class="form-horizontal" style="font-size: 12px;">
    <?php
    if (count($informacion) > 0) {
        
        
                        $fec_inicio_format = date("d/m/Y", strtotime($informacion['FECHA_INICIO']));
                        $fec_fin_format = date("d/m/Y", strtotime($informacion['FECHA_FIN']));
                        
        ?>

        <div class="form-group">
            <label class="control-label col-sm-3 col-xs-12 text-right"><b class="title_lbl">Nombre del instrumento:</b></label>
            <label class="control-label col-sm-9 col-xs-12 text-left"><?= $informacion['des_instrumento'] ?></label>
        </div>
        <div class="form-group">
            <label class="control-label col-sm-3 col-xs-12 text-right"><b class="title_lbl">Estrategia:</b></label>
            <label class="control-label col-sm-9 col-xs-12 text-left"><?= $informacion['des_estrategia'] ?></label>
        </div>
        <div class="form-group">
            <label class="control-label col-sm-3 col-xs-12 text-right"><b class="title_lbl">Intervención:</b></label>
            <label class="control-label col-sm-9 col-xs-12 text-left"><?= $informacion['des_intervencion'] ?></label>
        </div>
        <div class="form-group">
            <label class="control-label col-sm-3 col-xs-12 text-right"><b class="title_lbl">Ámbito:</b></label>
            <label class="control-label col-sm-3 col-xs-12 text-left"><?= $informacion['des_ambito'] ?></label>
            <label class="control-label col-sm-3 col-xs-12 text-right"><b class="title_lbl">Tipo de instrumento:</b></label>
            <label class="control-label col-sm-3 col-xs-12 text-left"><?= $informacion['des_tipo_instrumento'] ?></label>
        </div>
        <div class="form-group">
            <label class="control-label col-sm-3 col-xs-12 text-right"><b class="title_lbl">Informante:</b></label>
            <label class="control-label col-sm-3 col-xs-12 text-left"><?= $informacion['DESCRIPCION_INFORMANTE'] ?></label>
            <label class="control-label col-sm-3 col-xs-12 text-right"><b class="title_lbl">Meta total:</b></label>
            <label class="control-label col-sm-3 col-xs-12 text-left"><?= intval($t) ?></label>
        </div>
        <div class="form-group">
            <label class="control-label col-sm-3 col-xs-12 text-right"><b class="title_lbl">Fecha de inicio:</b></label>
            <label class="control-label col-sm-3 col-xs-12 text-left"><?= $fec_inicio_format ?></label>
            <label class="control-label col-sm-3 col-xs-12 text-right"><b class="title_lbl">Fecha fin:</b></label>
            <label class="control-label col-sm-3 col-xs-12 text-left"><?= $fec_fin_format ?></label>
        </div>

    <?php
}
?>
</form>